config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'destinations#index'
  resources :destinations
  namespace :api do
    namespace :v1 do
      resources :destinations, only: [:index, :show, :create, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
end

app/controllers/api/v1/destinations_controller.rb
class Api::V1::DestinationsController < ApplicationController
  def index
    render json: DestinationSerializer.render(Destination.all)
  end

  def show
    render json: DestinationSerializer.render(Destination.find(params[:id]))
  end

  def create
    destination = Destination.create(destination_params)
    render json: DestinationSerializer.render(destination)
  end

  def update
    destination = Destination.update(params[:id], destination_params)
    render json: DestinationSerializer.render(destination)
  end

  def destroy
    Destination.destroy(params[:id])
  end

  private

  def destination_params
    params.permit(:name, :zip, :description, :image_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  def index
    @destinations = Destination.all
  end

  def show
    destination = Destination.find(params[:id])
    zip = destination.zip
    @weather = WeatherFacade.fetch_weather(zip)
  end

  def new
    @destination = Destination.new
  end

  def edit
  end

  def create
    @destination = Destination.new(destination_params)
    if @destination.save
      redirect_to @destination, notice: 'Destination was successfully created.'
    else
      render :new
    end
  end

  def update
    if @destination.update(destination_params)
      redirect_to @destination, notice: 'Destination was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @destination.destroy
    redirect_to destinations_path, notice: 'Destination was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_destination
    @destination = Destination.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def destination_params
    params.require(:destination).permit(:name, :zip, :description, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/destinations/_form.html.erb
<%= form_for(destination) do |f| %>
  <% if destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<div class="container">
  <h1>Editing Destination</h1>

  <%= render 'form', destination: @destination %>

  <%= link_to 'Show', @destination %> |
  <%= link_to 'Back', destinations_path %>
</div>

app/views/destinations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <h1>All Destinations</h1>

  <div class="row">
  <% @destinations.each do |destination| %>
    <div class="col-sm-6 col-med-4 col-xs-12">
      <section id="destination-<%= destination.id %>">
        <h4><%= destination.name %></h4>
        <p><%= destination.zip %></p>
        <p><%= destination.description %></p>
        <%= link_to(image_tag(destination.image_url), destination_path(destination)) %>
        <div>
          <p><%= link_to 'Show', destination %></p>
          <p><%= link_to 'Edit', edit_destination_path(destination) %></p>
          <p><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        </div>
      </section>
    </div>
  <% end %>
  </div>
  <p><%= link_to 'New Destination', new_destination_path %></p>
</div>

app/views/destinations/new.html.erb
<div class="container">
  <h1>New Destination</h1>

  <%= render 'form', destination: @destination %>

  <%= link_to 'Back', destinations_path %>
</div>

app/views/destinations/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h3>
    <%= @destination.name %>
  </h3>

  <p>
    <strong>Zip:</strong>
    <%= @destination.zip %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @destination.description %>
  </p>

  <%= image_tag(@destination.image_url) %>

  <div class="row">
    <h4>Forecast for <%= @destination.name %>:</h4>
    <div class="weather">
      <p id="date">
      Date: <%= @weather.date %>
      </p>
      <p id="current-temp">
      Current Temperature: <%= @weather.current_temp %>° Fahrenheit
      </p>
      <p id="high-temp">
      High Temperature: <%= @weather.high_temp %>° Fahrenheit
      </p>
      <p id="low-temp">
      Low Temperature: <%= @weather.low_temp %>° Fahrenheit
      </p>
      <p id="description">
      Summary: <%= @weather.description %>
      </p>
      <p id="weather-image">
      <!%= image_tag("#{@image.url}", :alt => "Weather Image") %>
      </p>
    </div>
  </div>

  <div class="row">
    <%= link_to 'Edit', edit_destination_path(@destination) %> |
    <%= link_to 'Back', destinations_path %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Destination Planner</a>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DestinationPlanner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: 'layouts/nav' %>
    <%= yield %>
  </body>
</html>